{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "github-rate-limit-exporter.fullname" . }}
  {{- if .Values.podMonitor.namespace }}
  namespace: {{ .Values.podMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "github-rate-limit-exporter.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "github-rate-limit-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: http
    {{- if .Values.podMonitor.interval }}
    interval: {{ .Values.podMonitor.interval }}
    {{- end }}
    {{- if .Values.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
    {{- end }}
    path: {{ .Values.exporter.metricsPath }}
{{- end }}
