{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-rate-limit-exporter.fullname" . }}
  labels:
    {{- include "github-rate-limit-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.existingSecretKey }}: |
    {{- include "github-rate-limit-exporter.config" . | nindent 4 }}
{{- end }}
